### ISSUE TITLE
I use a mac environment and have many problems.

### ISSUE THREAD

**Issue by bjarne56** [D7EAD/liboai#13]
I use a mac environment and have many problems.
The compiler used is Clion

**Comment by D7EAD** [comment]
Hi!

Could you please provide a list of issues that you are facing. The library hasn't been tested on MacOS, and I would love to work towards portability for it.

**Comment by SpinnerX** [comment]
Hello!

I use a mac environment, and the problems I am coming across is mainly linking the curl and crp lib. Instructions on how to link the the liboai would also be useful.

**Comment by D7EAD** [comment]
> Hello!
> 
> I use a mac environment, and the problems I am coming across is mainly linking the curl and crp lib. Instructions on how to link the the liboai would also be useful.

Hi. 

As I am not a MacOS user, I cannot help with the specifics of linkage to the library as it is largely the same as linking to any other library. 

As for CPR, liboai no longer uses it--I have phased it out for cURL by itself. Speaking of cURL, it is available by default on MacOS and Xcode environments and you can get an idea of how to link to it here: https://stackoverflow.com/questions/5793760/including-libcurl-in-c-project

The process for compiling liboai into a static or dynamic library should be as straightforward as: 
* Loading the source into Xcode
* Including nlohmann-json (as it is pure C++)
* Including and linking to cURL
* Compiling for C++17 as a static or synamic library. 

Once you compile liboai, you should be able to link to it from another project and use it accordingly. 

If you have any platform-specific issues regarding the library, such as compile-time errors, please let me know as I can address those rather quickly.
