### ISSUE TITLE
Move liboai.h into includes directory for easier integration of the library

### ISSUE THREAD

**Issue by FunnyPixel** [D7EAD/liboai#14]
### Describe the feature or improvement you're requesting

Hi. Just a suggestion for more convenient includes hierarchy. Header` liboai.h` is not under includes dir which requires adding top dir into includes of MSVC to get this one in. Isn't it more natural to have all the includes under the same roof? If you accept PRs I can refactor it.
Best,
Mike.

**Comment by D7EAD** [comment]
Sure, why not!

Go ahead and make a PR for it if you'd like and I'd gladly test and accept it.
