### ISSUE TITLE
Deleted issues

### ISSUE THREAD

**Issue by FunnyPixel** [D7EAD/liboai#15]
### Describe the feature or improvement you're requesting

I am not sure if I get it right. Have you just deleted the issue I have submitted?
Also, I am unable to submit a bug report. The submit button is disabled.
I was just trying to get running with the basic auth test and there is a crash of memory in one of the classes in the lib.
Please allow people to submit tickets and suggestions.

**Comment by D7EAD** [comment]
I responded to your suggestion saying it was a good idea and closed it afterwards.

**Comment by FunnyPixel** [comment]
I see nothing here. The whole Issues list was empty after I have submitted. Weird.

**Comment by FunnyPixel** [comment]
Sorry, now I see it. Had to disable filtering.
I have filled all the fields. Will try again.
Thanks.
