### ISSUE TITLE
Documenting the rest of arguments for create_async

### ISSUE THREAD

**Issue by FunnyPixel** [D7EAD/liboai#19]
### Describe the feature or improvement you're requesting

Hi.
I am trying to learn how to use async methods. I see some optional arguments in create_async,which I don't completely understand.
Could please elaborate on these:

```
std::optional<std::function<bool(std::string, intptr_t)>> stream, //Is it a callback function? what is the purpose of its arguments?
std::optional<std::vector<std::string>> stop,  // what does this do?
std::optional<uint16_t> max_tokens, // what does this do?
std::optional<float> presence_penalty,// what does this do?
std::optional<float> frequency_penalty,// what does this do?
std::optional<std::unordered_map<std::string, int8_t>> logit_bias,// what does this do?
std::optional<std::string> user// what does this do?
```

I haven't found documentation regarding these.

Thanks.

**Comment by FunnyPixel** [comment]
Well,found it all in the OpenAI official guide. I thought stream is a callback that gets triggered on response. But that's not the case, is it?

**Comment by D7EAD** [comment]
> Well,found it all in the OpenAI official guide. I thought stream is a callback that gets triggered on response. But that's not the case, is it?

`stream` is a callback function that is called each time an SSE is received from OpenAI
 If you were to provide a callback to stream of the signature `bool(std::string, intptr_t)`, it would be called each time an SSE is received--such as for each token in a series of tokens making up a paragraph.

**Comment by D7EAD** [comment]
It would be a good addition to add extra code samples to the documentation to show the use of several of the parameters for component method.
