### ISSUE TITLE
Can't forward declare Conversation class

### ISSUE THREAD

**Issue by FunnyPixel** [D7EAD/liboai#20]
C++ doesn't allow forward declaration of nested classes.
Nesting of classes such as Conversation makes the API less flexible by forcing user to expose the API declaration in app headers just for the sake of defining member variables as pointers.

**Comment by D7EAD** [comment]
Should be fixed in 3966dcfd6c96d28abb72c34f989aaeaf19614261 and 1f3b4064beda45d7f17fb9bc39ad545781099f14.

**Comment by D7EAD** [comment]
Setting as inactive until activity resumes; assuming fixed post-commit.
