### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by JOo0ker** [D7EAD/liboai#23]
### Describe the bug

"e[1] = curl_easy_setopt(this->curl_, CURLOPT_PROXY, proxies_[protocol]);"

should be

“e[1] = curl_easy_setopt(this->curl_, CURLOPT_PROXY, proxies_[protocol].c_str());”

### To Reproduce

Bug in the "netimpl.cpp" file

### OS

windows10

### Library version

nope

**Comment by D7EAD** [comment]
Gotta love C variable parameters. Thanks for this.

Pushing a PR for it ASAP.

**Comment by D7EAD** [comment]
Should be fixed. Feel free to re-open if any more issues arise.
