### ISSUE TITLE
Why thi repo include nlohmann as library?  I can't build nlohmann success on widows.

### ISSUE THREAD

**Issue by xkungxfu** [D7EAD/liboai#35]
### Describe the feature or improvement you're requesting

[nlohmann](https://github.com/nlohmann)  is a header only library. I went to use it by downloading and include a json.hpp file on my projects.

how to avoid to build [nlohmann](https://github.com/nlohmann), only include it's header file?

**Comment by D7EAD** [comment]
The library uses nlohmann-json because it is a pure C++11 solution to JSON. 

You don't have to build nlohmann-json to use liboai, you can just download it using your standard package manager and use it. As long as it is in your standard package directory so it can be included via `#include <nlohmann/json.hpp>`, there should be no issue. 

Ensure that nlohmann is correctly installed on your system so your compiler and/or IDE can include it from the standard package directory.

**Comment by xkungxfu** [comment]
as your advice , I have to use a "standard package"? 
I use Qt Creator to create a project.  In my project it have only a file the name is "main.cpp". and when I want to use your repo, I can't find how , where what path to paste the repo files.

I saw your repo has a very different file directories and I don't know how to merge to my project.

does your repo must be built first or insert them into a "package"?

I haven't use any package manager before. what package manager I should use ?

**Comment by D7EAD** [comment]
> as your advice , I have to use a "standard package"? I use Qt Creator to create a project. In my project it have only a file the name is "main.cpp". and when I want to use your repo, I can't find how , where what path to paste the repo files.
> 
> I saw your repo has a very different file directories and I don't know how to merge to my project.
> 
> does your repo must be built first or insert them into a "package"?
> 
> I haven't use any package manager before. what package manager I should use ?
> 
> I am sorry for my poor English, hope you can understand my words.

For package management with C++, I tend to recommend people use VCPKG if they're on Windows. It automatically builds and includes installed packages to several IDEs on Windows, such as Visual Studio. I am unsure if it works with Qt Creator, so I can't provide help with that, but I don't see why it wouldn't.

You can build liboai separately as a static library and link your Qt project to it, or you can simply take the .h and .cpp files of liboai and build them with your Qt project; either way works.

**Comment by xkungxfu** [comment]
thank you . now I have one new problem . 
as your repo files system. all header files is in "include" directory. and all "cpp" file is in another directory.

so, if I must copy header files and ".cpp" files to same folder?

**Comment by D7EAD** [comment]
> thank you . now I have one new problem . as your repo files system. all header files is in "include" directory. and all "cpp" file is in another directory.
> 
> so, if I must copy header files and ".cpp" files to same folder?

As long as your compiler or IDE can find the .cpp files that are associated with the .h files, it should work regardless of how you structure it. However, I recommend preserving the structure of the repo as much as possible due to ease of organization.

**Comment by xkungxfu** [comment]
I got it. thank you.

**Comment by D7EAD** [comment]
For instance, I don't know how Qt Creator works, but you could have a file structure like this:

```
/Qt Creator
   /Project1
      /include
         /liboai
            / <contains the liboai folders 'include', 'core', and 'components'>
      /main.cpp
```

You could then include `liboai.h` from main.cpp via `#include "include/liboai/include/liboai.h` or, alternatively, you could set an option in Qt Creator (wherever it is) to an additional #include path to `include/liboai`, and then simply include liboai from main.cpp like `#include "include/liboai.h`.

**Comment by D7EAD** [comment]
Glad to hear. Enjoy the library.

**Comment by xkungxfu** [comment]
thank you again. it run ok now. 
I have a question about stream .  maybe open new issue later. 
now I have some test on the project.

**Comment by D7EAD** [comment]
If you have questions about other features of the library, feel free to open another issue.
