### ISSUE TITLE
Question about stream .

### ISSUE THREAD

**Issue by xkungxfu** [D7EAD/liboai#36]
### Describe the feature or improvement you're requesting

As you know, OpenAI's response is generally in the stream format. If JSON format is used, the response will become very slow. Such a long wait can make everyone lose interest in the software.

1. How can we add the stream parameter to the request to make OpenAI return data in the stream format? Should the stream parameter be added to the body or headers?

2. How will liboai handle the data returned by OpenAI in the stream format? How to implement printing output word by word?

**Comment by D7EAD** [comment]
You can provide a callback function to any API component that allows one. For instance, `Completions::create` allows you to provide a custom callback function that is called each time a new piece of streamed data is received. The callback provided must be of the signature:

```cpp
bool function_name(std::string s, intptr_t i);
```

I suggest you read the documentation [here](https://github.com/D7EAD/liboai/tree/main/documentation) for whichever methods you are interested in, as well as the examples for each. Keep in mind that, as of right now, for `ChatCompletions`, there is no way to update a `Conversation` object with streamed data. This will be added in the future.

**Comment by xkungxfu** [comment]
what you said is: 
we can use a call back to output piece by piece of a message to console, but we can't insert piece to "Conversation object" piece by piece?

Am I understanding this correctly?

**Comment by D7EAD** [comment]
> what you said is: we can use a call back to output piece by piece of a message to console, but we can't insert piece to "Conversation object" piece by piece?
> 
> Am I understanding this correctly?

Yes, this is a feature I am implementing currently.

**Comment by D7EAD** [comment]
Hi.

I am nearly done with the next update for the library. Expect new features, including appending streamed data to `Conversation`, within a day or so.

**Comment by xkungxfu** [comment]
very good. 

it must the first stream solution about c++ & openai.

even chatgpt can't give right answer.

**Comment by D7EAD** [comment]
Hi.

The newest update has been released. It includes many new functions, including `AppendStreamData`, and a new class. I have yet to write the documentation for it yet, but feel free to toy around with it until then.
