### ISSUE TITLE
DLL building error in VS 2019

### ISSUE THREAD

**Issue by gjeges** [D7EAD/liboai#44]
### Describe the bug

When I try to build a dll or a lib from the source code, I get errors. The errors are at chat.cpp line 666 and at response.cpp line 64
![image](https://github.com/D7EAD/liboai/assets/138122932/4ad3538a-0b73-4b05-9be8-6b6e25dde4d6)

### To Reproduce

1. Create new C++ empty Project in Visual Studio 19
2. Import all of the liboai .h and .cpp files
3. Set it to build .dll with C++17
4. Try to build the project

### Code snippets

```C++
std::ostream& liboai::operator<<(std::ostream& os, const Conversation& conv) {
	os << conv.GetRawConversation() << std::endl << (conv.HasFunctions() ? conv.GetRawFunctions() : "");

	return os;
}
```

```
std::ostream& liboai::operator<<(std::ostream& os, const Response& r) {
	!r.raw_json.empty() ? os << r.raw_json.dump(4) : os << "null";
	return os;
}
```
```


### OS

Windows

### Library version

all

**Comment by D7EAD** [comment]
I'm unable to reproduce this error. 

Are you perhaps building in Debug mode rather than Release mode? There's also the possibility that VS 2019's C++17 implementation could be the issue, as we've experienced some issues with it before.

**Comment by gjeges** [comment]
I built it in Release mode. I tried it to build on another computer with VS 2022 and it worked. Thanks for your answer.
